# Versão do Docker Compose
version: "3.8"

services:
  # Aplicação web da up.ai
  upai-app:
    # Constrói a imagem usando o Dockerfile do projeto
    build:
      context: .

    # Nome do container da aplicação
    container_name: upai-app

    # Reinicia automaticamente se cair
    restart: always

    # Porta externa 3001 apontando para porta interna 3000 do Next.js
    ports:
      - "3001:3000"
